apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: sandbox-secretstore
spec:
  provider:
    infisical:
      hostAPI: https://app.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: external-secrets
            name: auth-credentials
          clientSecret:
            key: clientSecret
            namespace: external-secrets
            name: auth-credentials
      secretsScope:
        projectSlug: sandbox
        environmentSlug: dev
        secretsPath: /
        recursive: true
