apiVersion: v1
kind: Secret
metadata:
    name: auth-credentials
    namespace: external-secrets
stringData:
    clientId: ENC[AES256_GCM,data:YVPUh5Hr8yOopuInT1/X2pM7PGQJYdtql0NtOQzHoS/z4HUM,iv:hyijtKJB5N2XcbD7JCDDXuyO3eJ8MBkyeMY7HmHmNjQ=,tag:/hZ+UbClXo4wjnqEgTadLg==,type:str]
    clientSecret: ENC[AES256_GCM,data:EtGsE7njzud+meunHiQRXq6ePx8trHZqnrKMqWaoomfUgYOY4uugrf/WhFq0ftx5zkkWfkDghPLPw7loqCLxZQ==,iv:CEFKNtr45U4CpgBzV9miOhyXMbSCNHCtnK2WGf/9NCE=,tag:zfMwC79yeBTAeFmINT5bGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNDJtS2YxRkQ2NVpoYloz
            MlUvZnF2cDB1c1JwUEI1YWNuUE55WjkrOGpVCndUYnR0dis1bU4vbW5LMWFPcXNU
            SjhVMVJBbzV4Ry9kSWszWEszN2NHRDQKLS0tIG1XdVhMOU0vUFQvb2tFU2Vmd0VC
            M3NDQXpKVGhRVVRrd3AwNnk5akNEMTQKMFEGLhwj5XLv5HzG1R88T3Rd+elyG855
            hqpZUnK7DOMG8ypBwi36eaKXHpfcnW1Q8i2fJFjX+KGHcA9s64OdfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zuac5y9eycfa77xwc8h0vsy0agkcwn7lgx3ptg03rkpgqzu25u8saa2kpy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T16:49:58Z"
    mac: ENC[AES256_GCM,data:1JmbnWOEJpFOyKTnlHIgwmI7+puMMnSErVFRAHep/Il6WpnZjzUVM6JWdF5zJJr8malmUlLoWpYflMK3rnJMr643PoDpXlNi2QVzFfSl2GCTFeEel1O13j3vrw6sL7dq0AcVYq0VAbCy3YHQhW7lgdeJlnue8esdmnlhdS+lMoA=,iv:NvGrPeK6TSJMQpAPn3om4prrTy1ydcJ3idtVAL9VjBU=,tag:cpLpRphMmWiBq2fgmVgDqA==,type:str]
    version: 3.13.3
