apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  releaseName: keycloak
  chart:
    spec:
      chart: keycloak
      version: "24.7.4"
      sourceRef:
        kind: HelmRepository
        name: keycloak
        namespace: keycloak
  interval: 10m
