apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 10m
  ref:
    tag: latest
  url: oci://registry-1.docker.io/bitnamicharts/keycloak
