apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-stage-data
  namespace: stage
spec:  
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi-stage
