apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - ../../base/keycloak/
  - certificate.yaml
  - certificate-root.yaml
  - issuer.yaml
patches:
  - path: release.yaml
