apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
  interval: 10m
  values:
    crds:
      enabled: true
    webhook:
      networkPolicy:
        enabled: true
    dns01RecursiveNameservers: "1.1.1.1:53, 8.8.8.8:53"
