apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - calico
  - cert-manager
  - cluster-maintenance
  - external-secrets
  - gateway-api
  - metallb
  - coredns
  - tailscale
