apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  secretStoreRef:
    name: sandbox-secretstore
    kind: ClusterSecretStore
  data:
    - secretKey: cloudflare-api-token
      remoteRef:
        key: /cf/cloudflare-api-token
