apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: sandbox-secretstore
    kind: ClusterSecretStore
  data:
    - secretKey: cloudflare-api-token
      remoteRef:
        key: cloudflare-api-token
