apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth
  namespace: tailscale
spec:
  secretStoreRef:
    name: sandbox-secretstore
    kind: ClusterSecretStore
  target:
    name: tailscale-operator-oauth
  data:
    - secretKey: client_id
      remoteRef:
        key: /remote_access/tailscale_oauth_client/client_id
    - secretKey: client_secret
      remoteRef:
        key: /remote_access/tailscale_oauth_client/client_secret
