apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth
  namespace: tailscale
spec:
  secretStoreRef:
    name: sandbox-secretstore
    kind: ClusterSecretStore
  target:
    name: tailscale-operator-oauth
  dataFrom:
    - extract:
        key: /remote_access/tailscale_oauth_client
