apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-db-credentials
  namespace: postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: sandbox-secretstore

  data:
    - secretKey: username
      remoteRef:
        key: /n8n/db_user
    - secretKey: password
      remoteRef:
        key: /n8n/db_password
