apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cnpg
spec:
  releaseName: cnpg
  chart:
    spec:
      chart: cnpg
      version: "0.24.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
  interval: 10m
  values:
    crds:
      enabled: true
