apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
  namespace: cloudflared
spec:
  secretStoreRef:
    name: sandbox-secretstore
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel
    template:
      data:
        credentials.json: |
          {"AccountTag":"{{ .AccountTag }}","TunnelSecret":"{{ .TunnelSecret }}","TunnelID":"{{ .TunnelID }}"}
  dataFrom:
    - extract:
        key: /cf/my-tunnel
