apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-dev
provisioner: nfs.csi.k8s.io
parameters:
  server: nfs-server-dev.kube-system.svc.cluster.local
  share: /export/volumes/dynamic/dev
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
