apiVersion: v1
kind: Endpoints
metadata:
  name: nfs-server
  namespace: kube-system
subsets:
- addresses:
  - ip: 192.168.0.66
  ports:
    - name: tcp-2049
      port: 2049
      protocol: TCP
    - name: tcp-111
      port: 111
      protocol: TCP
    - name: udp-111
      port: 111
      protocol: UDP
