apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
  namespace: cloudflared
spec:
  secretStoreRef:
    name: sandbox-secretstore
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: /cf/my-tunnel
#  data:
#    - secretKey: creds.yaml
#      remoteRef:
#        key: /cf/my-tunnel
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  secretStoreRef:
    name: sandbox-secretstore
    kind: ClusterSecretStore
  data:
    - secretKey: token
      remoteRef:
        key: /cf/sandbox-token
