apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
  namespace: cloudflared
spec:
  secretStoreRef:
    name: sandbox-secretstore
    kind: ClusterSecretStore
  data:
    - secretKey: creds.yaml
      remoteRef:
        key: /cf/my-tunnel
        property: creds.yaml
