apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-credentials
  namespace: keycloak-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: sandbox-secretstore

  data:
    - secretKey: username
      remoteRef:
        key: /keycloak/admin_user
    - secretKey: password
      remoteRef:
        key: /keycloak/admin_password
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: keycloak-admin-credentials
spec:
  namespaceSelector:
    matchLabels:
      app: keycloak
  secretStoreRef:
    kind: ClusterSecretStore
    name: sandbox-secretstore

  data:
    - secretKey: username
      remoteRef:
        key: /keycloak/admin_user
    - secretKey: password
      remoteRef:
        key: /keycloak/admin_password

