apiVersion: v1
kind: Service
metadata:
  name: talos-api
  namespace: tailscale
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/tags: "tag:k8s-operator"
spec:
  type: ExternalName
  externalName: talos-cp.internal
  ports:
    - port: 50000
      protocol: TCP
