apiVersion: apps/v1
kind: Deployment
metadata:
  name: bus
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      service: bus
  template:
    metadata:
      name: bus
      labels:
        service: bus
    spec:
      volumes:
        - name: bus-volume
          persistentVolumeClaim:
            claimName: pvc-nfs-dev-data
      containers:
        - name: bus
          image: miskers/test_image:latest
          ports:
            - containerPort: 8002
          volumeMounts:
            - name: bus-volume
              mountPath: "/mnt"
      
