apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-external-secret
  namespace: dev
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: sandbox-secretstore

  data:
    - secretKey: test_test
      remoteRef:
        key: /sandbox_secrets/test
