apiVersion: v1
kind: Pod
metadata:
  name: test-pvc-pod
  namespace: dev
spec:
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: pvc-nfs-static-data
  containers:
    - name: test-pod
      image: miskers/test_image
      ports:
        - containerPort: 8002
      volumeMounts:
        - name: test-volume
          mountPath: "/mnt"



