apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-static-data
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi  
  persistentVolumeReclaimPolicy: Retain
  nfs:
#    server: 192.168.0.66
    server: nfs-server.default.svc.cluster.local
#    path: "/export/volumes/static"
    path: "/"
