apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: databases
  namespace: flux-system
spec:
  interval: 60s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./databases/sandbox
  prune: true
