apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-secret
  namespace: pihole
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: sandbox-secretstore

  data:
    - secretKey: FTLCONF_webserver_api_password
      remoteRef:
        key: /pihole/webpassword
