apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  values:
    grafana:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - grafana-local-spt.lab
        paths:
          - /
      persistence:
        enabled: true
        storageClassName: default-kubernetes-sandbox-storageclass
        accessModes:
          - ReadWriteOnce
        size: 5Gi
      admin:
        existingSecret: grafana-admin-credentials
        passwordKey: admin_password
    alertmanager:
      enabled: false
    prometheus:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - prometheus-local-spt.lab
        paths:
          - /
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: default-kubernetes-sandbox-storageclass
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
