apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - calico
  - cert-manager
  - cnpg
  - external-secrets
  - gateway-api-crds
  - ingress-nginx
  - local-path-provisioner
  - metallb
  - metrics-server
  - nfs-driver
  - nfs-server-provisioner
  - nginx-gateway-fabric

