apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: first-role-binding
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aggregationRole
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: first-serviceaccount

