apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default-kubernetes-sandbox-storageclass
  annotations:
    storageclass.kubernetes.io/is-default-class: "true" 
provisioner: nfs.csi.k8s.io
parameters:
  server: nfs-server-provisioner.nfs-system.svc.cluster.local
  share: /export
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
