kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: restrict-access-to-ui-tier-only
  namespace: dev
spec:
  podSelector:
    matchLabels:
      service: bus
  policyTypes:
  - Egress
  egress:
  # Allow DNS resolution to any destination on port 53
  - ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow internal cluster communication
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8  # Replace with your actual cluster CIDR
