apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: duckdns-secret
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: sandbox-secretstore

  data:
    - secretKey: token
      remoteRef:
        key: /duckdns/duckdns-token
