apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: registry
  name: registry-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
